- hosts: workers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  connection: ssh
  gather_facts: yes

  tasks:
   - name: Copy join command from Ansiblehost to the worker nodes.
     become: yes
     copy:
       src: /tmp/join_command
       dest: /tmp/join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sh /tmp/join_command
     register: joined_or_not
